apiVersion: apps/v1
kind: Deployment
metadata:
  name: robojack
spec:
  selector:
    matchLabels:
      app: robojack
  template:
    metadata:
      labels:
        app: robojack
    spec:
      containers:
        - name: robojack
          image: ghcr.io/jack-gledhill/robojack:latest
          envFrom:
            - secretRef:
                name: robojack-config
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 100M
            limits:
              memory: 100M
          volumeMounts:
            - name: credentials
              mountPath: /data/credentials.json
              subPath: credentials.json
            - name: token
              mountPath: /data/token.json
              subPath: token.json
      volumes:
        - name: credentials
          secret:
            secretName: robojack-credentials
        - name: token
          persistentVolumeClaim:
            claimName: robojack-token