apiVersion: v1
kind: Service
metadata:
  name: robojack
  labels:
    app: robojack
spec:
  selector:
    app: robojack
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP